# Generated by Django 3.2.16 on 2022-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(default='0')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='dogs/')),
                ('breed_name', models.CharField(default='', max_length=250)),
                ('file_name', models.CharField(default='', max_length=250)),
                ('original_url', models.CharField(default='', max_length=250)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
